name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v0.8.1, etc.)
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests and quality checks
        run: make test-coverage lint mypy

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --dev

      - name: Build package
        run: make build

      - name: Check package with twine
        run: |
          uv tool install twine
          uv tool run twine check dist/*

      - name: Publish to PyPI (using token-based auth)
        if: "!contains(github.ref, 'test') && !contains(github.ref, 'dryrun')"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: true
          verbose: true
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish to TestPyPI (using token-based auth)
        if: "contains(github.ref, 'test') && !contains(github.ref, 'dryrun')"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verify-metadata: true
          verbose: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Dry run (build only)
        if: "contains(github.ref, 'dryrun')"
        run: |
          echo "Dry run mode - would publish these files:"
          ls -la dist/
          echo "Package contents:"
          uv tool run twine check dist/* --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts-${{ github.ref_name }}
          path: dist/